title: Master a Clean JavaScript Code
description: Learn best practices of writing a readable and maintainable code
tags: [ "JavaScript", "Clean code" ]
template:
  repo: webdev-200_2021-codewars-01-template
  name: webdev-200_2021-codewars-01
  description: 'A GitHub Labs robot-powered training repository for `WebDev-200_2021-Codewars-01` :robot:'

before:
  # - type: updateBranchProtection
  #   branch: main
  #   enforce_admins: true
  #   required_pull_request_reviews:
  #     include_admins: true
  - type: createIssue
    title: Welcome
    body: 001-welcome.md
    store:
      issue_1_url: '{{ result.data.html_url }}'
  - type: createFile
    filename: 002_01-hello-world_task.js
    new_name: 01-hello-world/task.js
steps:
  - title: Write an empty JavaScript function
    description: Let's start from the very beginning
    link: '{{ store.issue_1_url }}'
    event: push
    actions:
      - type: gate
        left: '%payload.commits[0]["modified"]%'
        operator: ===
        right: 01-hello-world/task.js

  # - title: Assign yourself
  #   description: Assign the first issue to yourself.
  #   event: issues.assigned
  #   link: '{{ store.issue_1_url }}'
  #   actions:
  #   - type: gate
  #     every: true
  #     gates:
  #     - left: '%payload.action%'
  #       operator: ===
  #       right: assigned
  #     - left: '%payload.assignee.login%'
  #       operator: ===
  #       right: '%user.login%'
  #     - left: '%payload.issue.id%'
  #       operator: ===
  #       right: '{{ store.issue_1_id }}'
  #     else:
  #     - type: respond
  #       with: 01_try-again.md
  #   - type: respond
  #     with: 01_nice-work.md

  # - title: Create an empty function
  #   description: Checking out the basic syntax
  #   event: push
  #   actions:
  #   - type: respond
  #     with: 02_nice-work.md
